# Generated by Django 5.2 on 2025-04-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
